CodeQ:
  PublishNotifier:
    notify:
      internalWorkspace:
        everyChange: false     # Send notification if publishing to any internal workspace
        onlyFirstChange: true # Send notification ONLY for the first time publishing to an internal workspace
      publicWorkspace: false  # Send notification for publishing to LIVE Workspace
    email:
      enabled: false
      senderName: 'Neos'
      senderAddress: 'no-reply@neos-server.com'
      notifyEmails: []
      subject: '%1$s has published changes'
      body: |+
        %1$s has published changes to the private workspace %2$s.
        Please review the changes and publish to live: %3$s
    slack:
      enabled: false
      postTo: []
        #example:
        #  webhookUrl: 'https://hooks.slack.com/services/...'
        #  clientSettings: [] # additional client configurations
      message: |+
        *%1$s* has published changes to the workspace *%2$s*.
        Please review the changes and publish to live: <%3$s|here>
