CodeQ:
  PublishNotifier:
    notify:
      internalWorkspaceWithoutUnpublishedChanges: true # Send notification for publishing to any internal workspace, which has no unpublished changes yet
      internalWorkspaceWithUnpublishedChanges: false # Send notification for publishing to any internal workspace, which already has unpublished changes
      publicWorkspace: false # Send notification for publishing to LIVE Workspace
    email:
      enabled: false
      senderName: 'Neos'
      senderAddress: 'no-reply@neos-server.com'
      notifyEmails: []
      subject: '%1$s has published changes'
      body: |+
        %1$s has published changes to the private workspace %2$s.
        Please review the changes and publish to live: %3$s
    slack:
      enabled: false
      postTo: []
        #example:
        #  webhookUrl: 'https://hooks.slack.com/services/...'
        #  clientSettings: [] # additional client configurations
      message: |+
        %1$s has published changes to the private workspace %2$s.
        Please review the changes and publish to live: %3$s
